"use client";
import {useEffect,useState} from 'react'; import {getBrowserSupabase} from '@/lib/supabase-browser';
import { Heart, Flag, Search, Send, ShieldCheck, MessageCircle } from 'lucide-react';
export default function Community(){const s=getBrowserSupabase();const [posts,setPosts]=useState<any[]>([]);const [content,setContent]=useState('');const [anonymous,setAnonymous]=useState(true);const [category,setCategory]=useState('General');const [q,setQ]=useState('');const [msg,setMsg]=useState('');
async function load(){const {data}=await s.from('posts').select('id,content,category,visibility,likes,comments,created_at,profiles(username,display_name)').eq('status','approved').order('created_at',{ascending:false});setPosts(data||[])} useEffect(()=>{load()},[]);
async function post(){const {data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return} if(content.trim().length<2)return;const {error}=await s.from('posts').insert({author_id:user.id,content,category,visibility:anonymous?'anonymous':'community'});setMsg(error?.message||'Submitted for moderation.');if(!error){setContent('');setTimeout(load,500)}}
async function like(id:string){const {data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return}const {data:ex}=await s.from('post_likes').select('post_id').eq('post_id',id).eq('user_id',user.id).maybeSingle();if(ex) await s.from('post_likes').delete().eq('post_id',id).eq('user_id',user.id);else await s.from('post_likes').insert({post_id:id,user_id:user.id});load()}
const shown=posts.filter(p=>!q||p.content.toLowerCase().includes(q.toLowerCase())||p.category.toLowerCase().includes(q.toLowerCase()));return <main className="shell community-page"><div className="page-hero"><div><span className="section-kicker">THE FEED</span><h1>Community</h1><p>Read, react and share — with moderation keeping the space respectful.</p></div><div className="searchbox"><Search size={17}/><input placeholder="Search posts..." value={q} onChange={e=>setQ(e.target.value)}/></div></div>
<div className="composer card"><div className="composer-top"><div className="avatar-lock">🤫</div><div><b>Share something with the community</b><span><ShieldCheck size={14}/> Public posts can be anonymous</span></div></div><textarea placeholder="What's on your mind?" value={content} onChange={e=>setContent(e.target.value)} maxLength={3000}/><div className="composer-bottom"><select value={category} onChange={e=>setCategory(e.target.value)}><option>General</option><option>Study</option><option>Coding</option><option>Career</option><option>Love</option><option>Confession</option><option>Campus</option></select><label className="check"><input type="checkbox" checked={anonymous} onChange={e=>setAnonymous(e.target.checked)}/> Anonymous</label><button className="btn primary" onClick={post}><Send size={16}/> Post</button></div>{msg&&<div className="notice">{msg}</div>}</div>
<div className="feed-list">{shown.map(p=><article className="card post-card" key={p.id}><div className="post-meta"><div className="avatar-lock">🤫</div><div><b>{p.visibility==='anonymous'?'Anonymous':p.profiles?.display_name||p.profiles?.username}</b><span>{new Date(p.created_at).toLocaleString()}</span></div><span className="pill">{p.category}</span></div><p className="post-content">{p.content}</p><div className="post-actions"><button onClick={()=>like(p.id)}><Heart size={17}/> {p.likes}</button><span><MessageCircle size={17}/> {p.comments}</span><button onClick={async()=>{const {data:{user}}=await s.auth.getUser(); if(!user)return; await s.from('reports').insert({reporter_id:user.id,post_id:p.id,reason:'Reported by user'});alert('Report sent.')}}><Flag size={16}/> Report</button></div></article>)}{shown.length===0&&<div className="empty card"><Search size={28}/><h3>No posts found</h3><p>Try another search or be the first to start a conversation.</p></div>}</div></main>}
